chore: update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,15 +14,27 @@ jobs:
     outputs:
       push: ${{ steps.push.outputs.push }}
     steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Check Dockerfile for HEALTHCHECK
+        run: |
+          if ! grep -q "HEALTHCHECK" ./Dockerfile; then
+            echo "::error::No HEALTHCHECK instruction found in Dockerfile - exiting..."
+            exit 1
+          else
+            echo "::notice::HEALTHCHECK instruction found in Dockerfile - proceeding..."
+          fi
+
       - name: Set push flag
         id: push
         run: |
           if [[ $GITHUB_REF == refs/tags/* ]]; then
             echo "push=true" >> "$GITHUB_OUTPUT"
-            echo "::notice::Image will be pushed after successful build!"
+            echo "::warning::Image will be pushed after successful build!"
           else
             echo "push=false" >> "$GITHUB_OUTPUT"
-            echo "::notice::Image will not be pushed!"
+            echo "::warning::Image will not be pushed!"
           fi
 
   # Naming -------------------------------------------------------
@@ -57,7 +69,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Push
-        uses: netwatching/action.docker.push@v2.1.2
+        uses: netwatching/action.docker.push@v2.1.3
         with:
           name: ${{ needs.name.outputs.name }}
           arch: ${{ matrix.arch }}
